title: Welcome to bluefin!
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to bluefin!"
      icon: "/path/to/icon"
      description: |
        This guided installer will help you get started with your new system.

  can-we-remove-your-system-flatpaks-and-user-fedora-remote:
    source: yafti.screen.consent
    values:
      title: Remove system Flatpaks and remove Fedora remotes
      description: |
        This step will remove all Fedora and Flathub system Flatpaks. It will not reinstall your flatpaks. It will also disable the system flatpaks in favor of user flatpaks. It will also remove Fedora user remote.
      actions:
        - run: flatpak remote-delete --system --force fedora
        - run: flatpak remote-delete --system --force flathub
        - run: flatpak remove --system --noninteractive --all
        - run: flatpak remote-delete --user --force fedora
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        user: true
        system: false
      groups:
        Core GNOME Apps:
          description: Core system applications for the GNOME desktop environment.
          default: true
          packages:
            - Calculator: org.gnome.Calculator
            - Calendar: org.gnome.Calendar
            - Camera: org.gnome.Snapshot
            - Characters: org.gnome.Characters
            - Clocks: org.gnome.clocks
            - Connections: org.gnome.Connections
            - Contacts: org.gnome.Contacts
            - Disk Usage Analyzer: org.gnome.baobab
            - Document Scanner: org.gnome.SimpleScan
            - Document Viewer: org.gnome.Evince
            - Extension Manager: com.mattjakeman.ExtensionManager
            - Font Viewer: org.gnome.font-viewer
            - Image Viewer: org.gnome.Loupe
            - Logs: org.gnome.Logs
            - Maps: org.gnome.Maps
            - Photos (Organizer): org.gnome.Photos
            - Sushi (Nautilus Previewer): org.gnome.NautilusPreviewer
            - Text Editor: org.gnome.TextEditor
            - Videos (Player): io.github.celluloid_player.Celluloid
            - Weather: org.gnome.Weather
        System Apps:
          description: System applications for all desktop environments.
          default: true
          packages:
            - Flatseal (Permission Manager): com.github.tchx84.Flatseal
            - WareHouse (Flatpack Manager): io.github.flattool.Warehouse
            - Media Writer: org.fedoraproject.MediaWriter
            - Impression: io.gitlab.adhami3310.Impression
            - Mission Center (System Resource Monitor): io.missioncenter.MissionCenter
            - Gear Lever (AppImage Manager): it.mijorus.gearlever
            - Vorta (BorgBackup GUI): com.borgbase.Vorta
            - Font Downloader: org.gustavoperedo.FontDownloader
        Development:
          description: Development applications
          default: true
          packages:
            - Box Buddy (Distrobox GUI): io.github.dvlv.boxbuddyrs
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Discord: com.discordapp.Discord
            - Steam: com.valvesoftware.Steam
            - Lutris: net.lutris.Lutris
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Bottles: com.usebottles.bottles
            - ProtonPlus (Wine/Proton Manager): com.vysp3r.ProtonPlus
            - SteamTinkerLaunch (Utility): com.valvesoftware.Steam.Utility.steamtinkerlaunch
            - Gamescope (Utility): org.freedesktop.Platform.VulkanLayer.gamescope//23.08
            - MangoHUD (Utility): org.freedesktop.Platform.VulkanLayer.MangoHud//23.08
            - vkBasalt (Utility): org.freedesktop.Platform.VulkanLayer.vkBasalt//23.08
        Office:
          description: Boost your productivity.
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Obsidian: md.obsidian.Obsidian
            - Slack: com.slack.Slack
            - Standard Notes: org.standardnotes.standardnotes
            - Thunderbird Email: org.mozilla.Thunderbird
            - Nextcloud: com.nextcloud.desktopclient.nextcloud

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      description: |
        You are all set.
